// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Brand Colour documents
 */
interface BrandColourDocumentData {
  /**
   * Colour code field in *Brand Colour*
   *
   * - **Field Type**: Text
   * - **Placeholder**:  (hex, rgb etc)
   * - **API ID Path**: brand_colour.colour_code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  colour_code: prismic.KeyTextField;
}

/**
 * Brand Colour document from Prismic
 *
 * - **API ID**: `brand_colour`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandColourDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BrandColourDocumentData>,
    "brand_colour",
    Lang
  >;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *Feature → Categories*
 */
export interface FeatureDocumentDataCategoriesItem {
  /**
   * Category field in *Feature → Categories*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.categories[].category
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;
}

type FeatureDocumentDataSlicesSlice = never;

/**
 * Content for Feature documents
 */
interface FeatureDocumentData {
  /**
   * Title field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Categories field in *Feature*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  categories: prismic.GroupField<Simplify<FeatureDocumentDataCategoriesItem>>;

  /**
   * Slice Zone field in *Feature*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FeatureDocumentDataSlicesSlice> /**
   * Featured Title field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.featured_title
   * - **Tab**: Featured
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  featured_title: prismic.RichTextField;

  /**
   * Featured Text field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.featured_text
   * - **Tab**: Featured
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_text: prismic.RichTextField;

  /**
   * Image field in *Feature*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.image
   * - **Tab**: Featured
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Feature document from Prismic
 *
 * - **API ID**: `feature`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeatureDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FeatureDocumentData>,
    "feature",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FeatureAreaSlice
  | TourSectionSlice
  | BannerSlice;

/**
 * Item in *Page → Page Sections*
 */
export interface PageDocumentDataPageSectionsItem {
  /**
   * Page Section field in *Page → Page Sections*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.page_sections[].page_section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_section: prismic.ContentRelationshipField<"page_section">;
}

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Page Sections field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.page_sections[]
   * - **Tab**: Page Sections
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  page_sections: prismic.GroupField<Simplify<PageDocumentDataPageSectionsItem>>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PageSectionDocumentDataSlicesSlice =
  | TourSectionSlice
  | TextSectionSlice
  | FeatureListSlice
  | BannerSlice;

/**
 * Content for Page Section documents
 */
interface PageSectionDocumentData {
  /**
   * Background colour field in *Page Section*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page_section.background_colour
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * PaddingY field in *Page Section*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page_section.padding_y
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_y: prismic.NumberField;

  /**
   * Slice Zone field in *Page Section*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page_section.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageSectionDocumentDataSlicesSlice>;
}

/**
 * Page Section document from Prismic
 *
 * - **API ID**: `page_section`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageSectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PageSectionDocumentData>,
    "page_section",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Newsletter Description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above the sign up form
   * - **API ID Path**: settings.newsletterDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletterDescription: prismic.RichTextField;

  /**
   * Newsletter Disclaimer field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Small text below sign up form
   * - **API ID Path**: settings.newsletterDisclaimer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletterDisclaimer: prismic.RichTextField /**
   * Social Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_text
   * - **Tab**: Socials
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  social_text: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TourDocumentDataSlicesSlice =
  | TourInfoSectionSlice
  | BannerSlice
  | TextSectionSlice
  | ImageSlice;

/**
 * Content for Tour documents
 */
interface TourDocumentData {
  /**
   * Title field in *Tour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Video field in *Tour*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;

  /**
   * Booking Link field in *Tour*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.booking_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  booking_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Tour*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TourDocumentDataSlicesSlice> /**
   * Feature Title field in *Tour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.feature_title
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  feature_title: prismic.KeyTextField;

  /**
   * Description field in *Tour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.description
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Feature Image field in *Tour*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.feature_image
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * Background Colour field in *Tour*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.background_colour
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * Opacity field in *Tour*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.opacity
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  opacity: prismic.SelectField<
    "0.1" | "0.2" | "0.3" | "0.4" | "0.5" | "0.6" | "0.7" | "0.8" | "0.9"
  >;
}

/**
 * Tour document from Prismic
 *
 * - **API ID**: `tour`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TourDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TourDocumentData>, "tour", Lang>;

export type AllDocumentTypes =
  | BrandColourDocument
  | CategoryDocument
  | FeatureDocument
  | NavigationDocument
  | PageDocument
  | PageSectionDocument
  | SettingsDocument
  | TourDocument;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Inner Text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.inner_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  inner_text: prismic.RichTextField;

  /**
   * Background Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Colour field in *Banner → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * Text Colour field in *Banner → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.text_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  text_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * opacity field in *Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.opacity
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  opacity: prismic.SelectField<
    "0.1" | "0.2" | "0.3" | "0.4" | "0.5" | "0.6" | "0.7" | "0.8" | "0.9"
  >;

  /**
   * Has Overlay field in *Banner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: banner.default.primary.has_overlay
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_overlay: prismic.BooleanField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *FeatureSection → Default → Primary*
 */
export interface FeatureAreaSliceDefaultPrimary {
  /**
   * Type field in *FeatureSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose from the dropdown
   * - **Default Value**: London
   * - **API ID Path**: feature_area.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"London" | "Colombia", "filled">;
}

/**
 * Default variation for FeatureSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureAreaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureAreaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureSection*
 */
type FeatureAreaSliceVariation = FeatureAreaSliceDefault;

/**
 * FeatureSection Shared Slice
 *
 * - **API ID**: `feature_area`
 * - **Description**: FeatureArea
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureAreaSlice = prismic.SharedSlice<
  "feature_area",
  FeatureAreaSliceVariation
>;

/**
 * Item in *FeatureList → Default → Primary → Featured Items*
 */
export interface FeatureListSliceDefaultPrimaryFeaturedItemsItem {
  /**
   * Featured Item field in *FeatureList → Default → Primary → Featured Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_list.default.primary.featured_items[].featured_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_item: prismic.ContentRelationshipField<"feature">;
}

/**
 * Primary content in *FeatureList → Default → Primary*
 */
export interface FeatureListSliceDefaultPrimary {
  /**
   * Title field in *FeatureList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Featured Items field in *FeatureList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_list.default.primary.featured_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_items: prismic.GroupField<
    Simplify<FeatureListSliceDefaultPrimaryFeaturedItemsItem>
  >;
}

/**
 * Default variation for FeatureList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureList*
 */
type FeatureListSliceVariation = FeatureListSliceDefault;

/**
 * FeatureList Shared Slice
 *
 * - **API ID**: `feature_list`
 * - **Description**: FeatureList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureListSlice = prismic.SharedSlice<
  "feature_list",
  FeatureListSliceVariation
>;

/**
 * Primary content in *Image → White → Primary*
 */
export interface ImageSliceWhitePrimary {
  /**
   * Image field in *Image → White → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.white.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * With Accent field in *Image → White → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.white.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  withAccent: prismic.BooleanField;
}

/**
 * White variation for Image Slice
 *
 * - **API ID**: `white`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceWhite = prismic.SharedSliceVariation<
  "white",
  Simplify<ImageSliceWhitePrimary>,
  never
>;

/**
 * Primary content in *Image → Light Slate → Primary*
 */
export interface ImageSliceLightSlatePrimary {
  /**
   * Image field in *Image → Light Slate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.lightSlate.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * With Accent field in *Image → Light Slate → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.lightSlate.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  withAccent: prismic.BooleanField;
}

/**
 * Light Slate variation for Image Slice
 *
 * - **API ID**: `lightSlate`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceLightSlate = prismic.SharedSliceVariation<
  "lightSlate",
  Simplify<ImageSliceLightSlatePrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceWhite | ImageSliceLightSlate;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *TextSection → Default → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
  /**
   * Text field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Background Colour field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * Text Colour field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.text_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  text_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * PaddingY field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.padding_y
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  padding_y: prismic.NumberField;
}

/**
 * Default variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextSection*
 */
type TextSectionSliceVariation = TextSectionSliceDefault;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: TextSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSlice = prismic.SharedSlice<
  "text_section",
  TextSectionSliceVariation
>;

/**
 * Item in *TourInfoSection → Default → Primary → Gallery Images*
 */
export interface TourInfoSectionSliceDefaultPrimaryGalleryImagesItem {
  /**
   * Image field in *TourInfoSection → Default → Primary → Gallery Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *TourInfoSection → Default → Primary → Included Section*
 */
export interface TourInfoSectionSliceDefaultPrimaryIncludedSectionItem {
  /**
   * Includes field in *TourInfoSection → Default → Primary → Included Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.included_section[].includes
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  includes: prismic.RichTextField;

  /**
   * Does Not Include field in *TourInfoSection → Default → Primary → Included Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.included_section[].does_not_include
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  does_not_include: prismic.RichTextField;
}

/**
 * Primary content in *TourInfoSection → Default → Primary*
 */
export interface TourInfoSectionSliceDefaultPrimary {
  /**
   * Overview field in *TourInfoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.overview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  overview: prismic.RichTextField;

  /**
   * Dates field in *TourInfoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.dates
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  dates: prismic.RichTextField;

  /**
   * Price field in *TourInfoSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Gallery Images field in *TourInfoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.gallery_images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_images: prismic.GroupField<
    Simplify<TourInfoSectionSliceDefaultPrimaryGalleryImagesItem>
  >;

  /**
   * Included Section field in *TourInfoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.included_section[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  included_section: prismic.GroupField<
    Simplify<TourInfoSectionSliceDefaultPrimaryIncludedSectionItem>
  >;

  /**
   * Background Colour field in *TourInfoSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField;

  /**
   * Text Colour field in *TourInfoSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_info_section.default.primary.text_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  text_colour: prismic.ContentRelationshipField;
}

/**
 * Default variation for TourInfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourInfoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TourInfoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TourInfoSection*
 */
type TourInfoSectionSliceVariation = TourInfoSectionSliceDefault;

/**
 * TourInfoSection Shared Slice
 *
 * - **API ID**: `tour_info_section`
 * - **Description**: TourInfoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourInfoSectionSlice = prismic.SharedSlice<
  "tour_info_section",
  TourInfoSectionSliceVariation
>;

/**
 * Item in *TourSection → Default → Primary → Tours*
 */
export interface TourSectionSliceDefaultPrimaryToursItem {
  /**
   * Tour field in *TourSection → Default → Primary → Tours*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.tours[].tour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tour: prismic.ContentRelationshipField<"tour">;
}

/**
 * Primary content in *TourSection → Default → Primary*
 */
export interface TourSectionSliceDefaultPrimary {
  /**
   * Title field in *TourSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tours field in *TourSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.tours[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tours: prismic.GroupField<Simplify<TourSectionSliceDefaultPrimaryToursItem>>;

  /**
   * Background Colour field in *TourSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;
}

/**
 * Default variation for TourSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TourSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TourSection*
 */
type TourSectionSliceVariation = TourSectionSliceDefault;

/**
 * TourSection Shared Slice
 *
 * - **API ID**: `tour_section`
 * - **Description**: TourSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourSectionSlice = prismic.SharedSlice<
  "tour_section",
  TourSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BrandColourDocument,
      BrandColourDocumentData,
      CategoryDocument,
      CategoryDocumentData,
      FeatureDocument,
      FeatureDocumentData,
      FeatureDocumentDataCategoriesItem,
      FeatureDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocumentDataPageSectionsItem,
      PageSectionDocument,
      PageSectionDocumentData,
      PageSectionDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      TourDocument,
      TourDocumentData,
      TourDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      FeatureAreaSlice,
      FeatureAreaSliceDefaultPrimary,
      FeatureAreaSliceVariation,
      FeatureAreaSliceDefault,
      FeatureListSlice,
      FeatureListSliceDefaultPrimaryFeaturedItemsItem,
      FeatureListSliceDefaultPrimary,
      FeatureListSliceVariation,
      FeatureListSliceDefault,
      ImageSlice,
      ImageSliceWhitePrimary,
      ImageSliceLightSlatePrimary,
      ImageSliceVariation,
      ImageSliceWhite,
      ImageSliceLightSlate,
      TextSectionSlice,
      TextSectionSliceDefaultPrimary,
      TextSectionSliceVariation,
      TextSectionSliceDefault,
      TourInfoSectionSlice,
      TourInfoSectionSliceDefaultPrimaryGalleryImagesItem,
      TourInfoSectionSliceDefaultPrimaryIncludedSectionItem,
      TourInfoSectionSliceDefaultPrimary,
      TourInfoSectionSliceVariation,
      TourInfoSectionSliceDefault,
      TourSectionSlice,
      TourSectionSliceDefaultPrimaryToursItem,
      TourSectionSliceDefaultPrimary,
      TourSectionSliceVariation,
      TourSectionSliceDefault,
    };
  }
}
