// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Brand Colour documents
 */
interface BrandColourDocumentData {
  /**
   * Colour code field in *Brand Colour*
   *
   * - **Field Type**: Text
   * - **Placeholder**:  (hex, rgb etc)
   * - **API ID Path**: brand_colour.colour_code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  colour_code: prismic.KeyTextField;
}

/**
 * Brand Colour document from Prismic
 *
 * - **API ID**: `brand_colour`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandColourDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BrandColourDocumentData>,
    "brand_colour",
    Lang
  >;

type FeatureDocumentDataSlicesSlice = never;

/**
 * Content for Feature documents
 */
interface FeatureDocumentData {
  /**
   * Title field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * `slices` field in *Feature*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FeatureDocumentDataSlicesSlice> /**
   * Featured Title field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.featured_title
   * - **Tab**: Featured
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  featured_title: prismic.RichTextField;

  /**
   * Featured Text field in *Feature*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.featured_text
   * - **Tab**: Featured
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_text: prismic.RichTextField;

  /**
   * Image field in *Feature*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.image
   * - **Tab**: Featured
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Feature document from Prismic
 *
 * - **API ID**: `feature`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeatureDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FeatureDocumentData>,
    "feature",
    Lang
  >;

type FeaturedBlockDocumentDataSlicesSlice = FeaturedBlockSlice;

/**
 * Content for Featured Block documents
 */
interface FeaturedBlockDocumentData {
  /**
   * Title field in *Featured Block*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_block.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Featured Block*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_block.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FeaturedBlockDocumentDataSlicesSlice>;
}

/**
 * Featured Block document from Prismic
 *
 * - **API ID**: `featured_block`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeaturedBlockDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FeaturedBlockDocumentData>,
    "featured_block",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FeaturedSectionSlice
  | TourSectionSlice
  | BannerSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Newsletter Description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above the sign up form
   * - **API ID Path**: settings.newsletterDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletterDescription: prismic.RichTextField;

  /**
   * Newsletter Disclaimer field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Small text below sign up form
   * - **API ID Path**: settings.newsletterDisclaimer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletterDisclaimer: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TourDocumentDataSlicesSlice = BannerSlice | TextSectionSlice | ImageSlice;

/**
 * Content for Tour documents
 */
interface TourDocumentData {
  /**
   * Title field in *Tour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Video field in *Tour*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;

  /**
   * Slice Zone field in *Tour*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TourDocumentDataSlicesSlice> /**
   * Feature Title field in *Tour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.feature_title
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  feature_title: prismic.KeyTextField;

  /**
   * Description field in *Tour*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.description
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Feature Image field in *Tour*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.feature_image
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * Background Colour field in *Tour*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.background_colour
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * Opacity field in *Tour*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: tour.opacity
   * - **Tab**: Feature Block
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  opacity: prismic.SelectField<
    "0.1" | "0.2" | "0.3" | "0.4" | "0.5" | "0.6" | "0.7" | "0.8" | "0.9"
  >;
}

/**
 * Tour document from Prismic
 *
 * - **API ID**: `tour`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TourDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TourDocumentData>, "tour", Lang>;

export type AllDocumentTypes =
  | BrandColourDocument
  | FeatureDocument
  | FeaturedBlockDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument
  | TourDocument;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Inner Text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.inner_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  inner_text: prismic.RichTextField;

  /**
   * Background Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Colour field in *Banner → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * opacity field in *Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.opacity
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  opacity: prismic.SelectField<
    "0.1" | "0.2" | "0.3" | "0.4" | "0.5" | "0.6" | "0.7" | "0.8" | "0.9"
  >;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Item in *FeaturedBlock → Default → Primary → Featured Items*
 */
export interface FeaturedBlockSliceDefaultPrimaryFeaturedItemsItem {
  /**
   * Featured field in *FeaturedBlock → Default → Primary → Featured Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_block.default.primary.featured_items[].featured
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured: prismic.ContentRelationshipField<"feature">;
}

/**
 * Primary content in *FeaturedBlock → Default → Primary*
 */
export interface FeaturedBlockSliceDefaultPrimary {
  /**
   * Title field in *FeaturedBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Featured Items field in *FeaturedBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_block.default.primary.featured_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_items: prismic.GroupField<
    Simplify<FeaturedBlockSliceDefaultPrimaryFeaturedItemsItem>
  >;
}

/**
 * Default variation for FeaturedBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedBlock*
 */
type FeaturedBlockSliceVariation = FeaturedBlockSliceDefault;

/**
 * FeaturedBlock Shared Slice
 *
 * - **API ID**: `featured_block`
 * - **Description**: FeaturedBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedBlockSlice = prismic.SharedSlice<
  "featured_block",
  FeaturedBlockSliceVariation
>;

/**
 * Item in *FeaturedSection → Default → Primary → Featured Blocks*
 */
export interface FeaturedSectionSliceDefaultPrimaryFeaturedBlocksItem {
  /**
   * Featured Block field in *FeaturedSection → Default → Primary → Featured Blocks*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.featured_blocks[].featured_block
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_block: prismic.ContentRelationshipField<"featured_block">;
}

/**
 * Primary content in *FeaturedSection → Default → Primary*
 */
export interface FeaturedSectionSliceDefaultPrimary {
  /**
   * Title field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Featured Blocks field in *FeaturedSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_section.default.primary.featured_blocks[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_blocks: prismic.GroupField<
    Simplify<FeaturedSectionSliceDefaultPrimaryFeaturedBlocksItem>
  >;
}

/**
 * Default variation for FeaturedSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedSection*
 */
type FeaturedSectionSliceVariation = FeaturedSectionSliceDefault;

/**
 * FeaturedSection Shared Slice
 *
 * - **API ID**: `featured_section`
 * - **Description**: FeaturedSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSectionSlice = prismic.SharedSlice<
  "featured_section",
  FeaturedSectionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introductory text for the page
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → With Button → Primary*
 */
export interface HeroSliceWithButtonPrimary {
  /**
   * Text field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Introductory text for the page
   * - **API ID Path**: hero.withButton.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Text field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withButton.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withButton.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Image field in *Hero → With Button → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.withButton.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * With Button variation for Hero Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithButton = prismic.SharedSliceVariation<
  "withButton",
  Simplify<HeroSliceWithButtonPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceWithButton;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Image → White → Primary*
 */
export interface ImageSliceWhitePrimary {
  /**
   * Image field in *Image → White → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.white.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * With Accent field in *Image → White → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.white.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  withAccent: prismic.BooleanField;
}

/**
 * White variation for Image Slice
 *
 * - **API ID**: `white`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceWhite = prismic.SharedSliceVariation<
  "white",
  Simplify<ImageSliceWhitePrimary>,
  never
>;

/**
 * Primary content in *Image → Light Slate → Primary*
 */
export interface ImageSliceLightSlatePrimary {
  /**
   * Image field in *Image → Light Slate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.lightSlate.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * With Accent field in *Image → Light Slate → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.lightSlate.primary.withAccent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  withAccent: prismic.BooleanField;
}

/**
 * Light Slate variation for Image Slice
 *
 * - **API ID**: `lightSlate`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceLightSlate = prismic.SharedSliceVariation<
  "lightSlate",
  Simplify<ImageSliceLightSlatePrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceWhite | ImageSliceLightSlate;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *TextSection → Default → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
  /**
   * Text field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Background Colour field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;

  /**
   * Text Colour field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.text_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  text_colour: prismic.ContentRelationshipField<"brand_colour">;
}

/**
 * Default variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextSection*
 */
type TextSectionSliceVariation = TextSectionSliceDefault;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: TextSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSectionSlice = prismic.SharedSlice<
  "text_section",
  TextSectionSliceVariation
>;

/**
 * Item in *TextWithFeatures → Default → Primary → Features*
 */
export interface TextWithFeaturesSliceDefaultPrimaryFeaturesItem {
  /**
   * Feature Description field in *TextWithFeatures → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of a feature
   * - **API ID Path**: text_with_features.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *TextWithFeatures → Default → Primary*
 */
export interface TextWithFeaturesSliceDefaultPrimary {
  /**
   * Icon field in *TextWithFeatures → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_features.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Text field in *TextWithFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Primary text with rich formatting
   * - **API ID Path**: text_with_features.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Features field in *TextWithFeatures → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_features.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<TextWithFeaturesSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for TextWithFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithFeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithFeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextWithFeatures*
 */
type TextWithFeaturesSliceVariation = TextWithFeaturesSliceDefault;

/**
 * TextWithFeatures Shared Slice
 *
 * - **API ID**: `text_with_features`
 * - **Description**: TextWithFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithFeaturesSlice = prismic.SharedSlice<
  "text_with_features",
  TextWithFeaturesSliceVariation
>;

/**
 * Primary content in *TextWithImage → Default → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text displayed next to image
   * - **API ID Path**: text_with_image.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation = TextWithImageSliceDefault;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

/**
 * Item in *TourSection → Default → Primary → Tours*
 */
export interface TourSectionSliceDefaultPrimaryToursItem {
  /**
   * Tour field in *TourSection → Default → Primary → Tours*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.tours[].tour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tour: prismic.ContentRelationshipField<"tour">;
}

/**
 * Primary content in *TourSection → Default → Primary*
 */
export interface TourSectionSliceDefaultPrimary {
  /**
   * Title field in *TourSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tours field in *TourSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.tours[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tours: prismic.GroupField<Simplify<TourSectionSliceDefaultPrimaryToursItem>>;

  /**
   * Background Colour field in *TourSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_section.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_colour: prismic.ContentRelationshipField<"brand_colour">;
}

/**
 * Default variation for TourSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TourSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TourSection*
 */
type TourSectionSliceVariation = TourSectionSliceDefault;

/**
 * TourSection Shared Slice
 *
 * - **API ID**: `tour_section`
 * - **Description**: TourSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TourSectionSlice = prismic.SharedSlice<
  "tour_section",
  TourSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BrandColourDocument,
      BrandColourDocumentData,
      FeatureDocument,
      FeatureDocumentData,
      FeatureDocumentDataSlicesSlice,
      FeaturedBlockDocument,
      FeaturedBlockDocumentData,
      FeaturedBlockDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      TourDocument,
      TourDocumentData,
      TourDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      FeaturedBlockSlice,
      FeaturedBlockSliceDefaultPrimaryFeaturedItemsItem,
      FeaturedBlockSliceDefaultPrimary,
      FeaturedBlockSliceVariation,
      FeaturedBlockSliceDefault,
      FeaturedSectionSlice,
      FeaturedSectionSliceDefaultPrimaryFeaturedBlocksItem,
      FeaturedSectionSliceDefaultPrimary,
      FeaturedSectionSliceVariation,
      FeaturedSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceWithButtonPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithButton,
      ImageSlice,
      ImageSliceWhitePrimary,
      ImageSliceLightSlatePrimary,
      ImageSliceVariation,
      ImageSliceWhite,
      ImageSliceLightSlate,
      TextSectionSlice,
      TextSectionSliceDefaultPrimary,
      TextSectionSliceVariation,
      TextSectionSliceDefault,
      TextWithFeaturesSlice,
      TextWithFeaturesSliceDefaultPrimaryFeaturesItem,
      TextWithFeaturesSliceDefaultPrimary,
      TextWithFeaturesSliceVariation,
      TextWithFeaturesSliceDefault,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TourSectionSlice,
      TourSectionSliceDefaultPrimaryToursItem,
      TourSectionSliceDefaultPrimary,
      TourSectionSliceVariation,
      TourSectionSliceDefault,
    };
  }
}
