// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  feature_area: dynamic(() => import("./FeatureSection")),
  feature_list: dynamic(() => import("./FeatureList")),
  image: dynamic(() => import("./Image")),
  text_section: dynamic(() => import("./TextSection")),
  tour_info_section: dynamic(() => import("./TourInfoSection")),
  tour_section: dynamic(() => import("./TourSection")),
};
